services:
  postgres:
    image: postgres:15
    container_name: synprod_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-synprod}
      POSTGRES_USER: ${POSTGRES_USER:-synprod}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: